theme: jekyll-theme-midnight
show_downloads: true
title: VMPK for Android
tagline: This is the Java version of VMPK, ported to the Android operating system.
description: Virtual MIDI Piano Keyboard for Android is a MIDI events generator simulating a MIDI controller. It generates sound with the help of an embedded software MIDI synthesizer (Sonivox EAS) or sends MIDI events to the local network using a compatible IPMIDI protocol.


